version: '3'

services:
    postgres:
        image: 'postgres:9.6'
        env_file: 
            - '.env'
        volumes:
            - 'postgres:/var/lib/postgresql/data'
        ports:
            - '5432:5432'

    redis:
        image: 'redis:3.0-alpine'
        command: redis-server --requirepass devpassword
        volumes:
            - 'redis:/var/lib/redis/data'
        ports:
            - '6379:6379'

    website:
        build: .
        command: >
            flask run --host=0.0.0.0
        env_file: 
            - '.env'
        volumes:
            - .:/snakeeyes
        ports:
            - '5000:5000'
        
    celery:
        build: .
        command: celery worker -l info -A snakeeyes.blueprints.contact.tasks
        env_file: 
            - '.env'
        volumes: 
            - '.:/snakeeyes'

volumes:
    postgres:
    redis: